# Generated by Django 4.2.7 on 2024-01-26 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chromosome",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("chromName", models.CharField(max_length=200)),
                ("startPos", models.IntegerField(default=1)),
                ("endPos", models.IntegerField()),
                (
                    "strand",
                    models.IntegerField(
                        choices=[(1, "Sense"), (-1, "Antisense")], default=1
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gene",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("geneName", models.CharField(max_length=200)),
                ("geneSymbol", models.CharField(max_length=100)),
                ("geneBiotype", models.CharField(max_length=200)),
                (
                    "strand",
                    models.IntegerField(
                        choices=[(1, "Sense"), (-1, "Antisense")], default=1
                    ),
                ),
                ("startPos", models.IntegerField()),
                ("endPos", models.IntegerField()),
                ("description", models.CharField(max_length=700)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Assignable"),
                            (1, "Being annotated"),
                            (2, "Being corrected"),
                            (3, "Submitted to a validator"),
                            (4, "Validated"),
                        ],
                        default=0,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genome",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("species", models.CharField(max_length=200)),
                ("strain", models.CharField(max_length=200)),
                ("substrain", models.CharField(max_length=200)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Not annotated"),
                            (1, "In work"),
                            (2, "Validated"),
                        ],
                        default=0,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Peptide",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("transcriptName", models.CharField(max_length=200)),
                ("transcriptBiotype", models.CharField(max_length=200)),
                (
                    "idGene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.gene"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "email",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("firstName", models.CharField(max_length=50)),
                ("lastName", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=15)),
                ("phoneNumber", models.IntegerField()),
                (
                    "role",
                    models.IntegerField(
                        choices=[
                            (0, "Reader"),
                            (1, "Annotator"),
                            (2, "Validator"),
                            (3, "Admin"),
                        ],
                        default=0,
                    ),
                ),
                ("lastConnexion", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="PeptideSeq",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("sequence", models.CharField(max_length=1000000)),
                (
                    "idPeptide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.peptide"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NucleotidicSeq",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("sequence", models.CharField(max_length=100000000)),
                (
                    "idGene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.gene"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "type",
                    models.IntegerField(
                        choices=[(0, "Automatic"), (1, "User")], default=0
                    ),
                ),
                (
                    "emailAuthor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.user"
                    ),
                ),
                (
                    "idGene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.gene"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="gene",
            name="emailAnnotator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_annotator",
                to="main.user",
            ),
        ),
        migrations.AddField(
            model_name="gene",
            name="emailValidator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_validator",
                to="main.user",
            ),
        ),
        migrations.AddField(
            model_name="gene",
            name="idChrom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.chromosome"
            ),
        ),
        migrations.CreateModel(
            name="ChromosomeSeq",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("sequence", models.CharField(max_length=10000000000)),
                (
                    "idChrom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.chromosome",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chromosome",
            name="idGenome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.genome"
            ),
        ),
        migrations.AddConstraint(
            model_name="chromosome",
            constraint=models.UniqueConstraint(
                models.F("idGenome"),
                models.F("chromName"),
                name="unique_name_of_chromosome_in_genome",
            ),
        ),
    ]
