# Generated by Django 4.2.7 on 2024-02-16 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[
                            (0, "Reader"),
                            (1, "Annotator"),
                            (2, "Validator"),
                            (3, "Admin"),
                        ],
                        default=0,
                    ),
                ),
                ("researchCentre", models.CharField(blank=True, max_length=50)),
                ("firstName", models.CharField(max_length=50)),
                ("lastName", models.CharField(max_length=50)),
                ("phoneNumber", models.CharField(blank=True, max_length=12)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Chromosome",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("chromName", models.CharField(max_length=200)),
                ("startPos", models.IntegerField(default=1)),
                ("endPos", models.IntegerField()),
                (
                    "strand",
                    models.IntegerField(
                        choices=[(1, "Sense"), (-1, "Antisense")], default=1
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gene",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("geneName", models.CharField(max_length=200)),
                ("geneSymbol", models.CharField(blank=True, max_length=100)),
                ("geneBiotype", models.CharField(blank=True, max_length=200)),
                (
                    "strand",
                    models.IntegerField(
                        choices=[(1, "Sense"), (-1, "Antisense")], default=1
                    ),
                ),
                ("startPos", models.IntegerField()),
                ("endPos", models.IntegerField()),
                ("descriptionGene", models.CharField(blank=True, max_length=1000)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Not annotated"),
                            (1, "Being annotated"),
                            (2, "Being corrected"),
                            (3, "Submitted to a validator"),
                            (4, "Validated"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "emailAnnotator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_annotator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "emailValidator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_validator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "idChrom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.chromosome",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genome",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("species", models.CharField(max_length=200)),
                ("strain", models.CharField(blank=True, max_length=200)),
                ("substrain", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Not annotated"),
                            (1, "In work"),
                            (2, "Validated"),
                        ],
                        default=0,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Peptide",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("transcriptName", models.CharField(max_length=200)),
                ("transcriptBiotype", models.CharField(blank=True, max_length=200)),
                ("descriptionPep", models.CharField(blank=True, max_length=1000)),
                (
                    "idGene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.gene"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PeptideSeq",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("sequence", models.CharField(max_length=1000000)),
                (
                    "idPeptide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.peptide"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NucleotidicSeq",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("sequence", models.CharField(max_length=100000000)),
                (
                    "idGene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.gene"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.IntegerField(
                        choices=[(0, "Automatic"), (1, "User")], default=0
                    ),
                ),
                (
                    "emailAuthor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "idGene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.gene"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChromosomeSeq",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("sequence", models.CharField(max_length=10000000000)),
                (
                    "idChrom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.chromosome",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chromosome",
            name="idGenome",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.genome"
            ),
        ),
        migrations.AddConstraint(
            model_name="chromosome",
            constraint=models.UniqueConstraint(
                models.F("idGenome"),
                models.F("chromName"),
                name="unique_name_of_chromosome_in_genome",
            ),
        ),
    ]
